version: '2'
services: 
  backend-app: 
    build: ./server
    container_name: school-backend
    ports: 
      - "3000:3000"
    restart: always
  frontend-app: 
    build: ./angular-app
    container_name: angular-frontend
    ports: 
      - "4200:4200"
    restart: always
  mongo: 
    container_name: mongo
    image: "mongo:3.4.1"
    ports: 
      - "27017:27017"